[package]
name = "autoformalization"
version = "0.1.0"
lean_version = "leanprover/lean4:stable"

[dependencies]
mathlib = { git = "https://github.com/leanprover-community/mathlib4.git", rev = "master" }

[lean-pkg]
name = "autoformalization"
version = "0.1"

[[lean_lib]]
name = "Autoformalization"

[[lean_exe]]
name = "autoformalization"
root = "Main"